services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: nest-boilerplate-app
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nest_boilerplate?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_TLS=false
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=devsecret_but_secure_enough_for_livekit_connection_fix
    depends_on:
      - db
      - redis
      - livekit
    networks:
      - nest-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: nest-boilerplate-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_boilerplate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nest-boilerplate-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nest-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
       
  livekit:
    image: livekit/livekit-server:v1.4
    container_name: livekit-server

    environment:
      LIVEKIT_KEYS: devkey:devsecret
      LIVEKIT_RTC_USE_EXTERNAL_IP: "true"
      LIVEKIT_LOG_LEVEL: info

    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-60000:50000-60000/udp"

    networks:
      - nest-network

    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  nest-network:
    driver: bridge

